; Función que regresa el nodo (o estado) con el máximo valor, dado sus 'hijos'.
; -∞ = most-negative-fixnum
; +∞ = most-positive-fixnum
(defun minValue (state a b)
  (print 'Min)
  (when (terminalTest state)
    (setf (third state) (utility state))
    (print 'Utilidad1)
    (print state)
    (print 'FinUtilidad)
    (push state allSuccessors)
    (return-from minValue (third state)))
  (let ((v most-positive-fixnum))
    (mapcar #'(lambda (s)
      (setq v (min v (maxValue s a b)))
      (when (<= v a)
        (setf (third state) v)
        (print 'Utilidad2)
        (print state)
        (print 'FinUtilidad)
        (push state allSuccessors)
        (return-from minValue v))
      (setq b (min b v))) (successors state))
    (setf (third state) v)
    (print 'Utilidad3)
    (print state)
    (print 'FinUtilidad)
    (push state allSuccessors)
    (return-from minValue v)))
