(Defun imprime(lst)
(setq abuelos nil padres nil hijos nil)
(push '_ hijos)
(getLvl lst)
(print (reverse abuelos))
(print 'LISTO))

(Defun getLvl(lst)
(loop
  (when (null lst)
    (if (eq (car (last hijos)) '_)
      (let ((hijosTmp (reverse hijos)) )
        (pop hijosTmp)
        (setq hijos (reverse hijosTmp))
        (if (not (null hijos))
          (push '_ hijos))
        (if (not (null abuelos))
          (print (reverse abuelos)))
        (setq abuelos padres)
        (setq padres nil)))
    (return 8))
  (setq elem (pop lst))
  (cond ((null elem) )
    ((atom elem) (push elem padres))
    (t (push elem hijos))))

(if (not (null hijos))
  (let ((hijosTmp (reverse hijos)) )
    (setq nuevoHijo (pop hijosTmp))
    (setq hijos (reverse hijosTmp))
    (getLvl nuevoHijo))))
